### PR TITLE
doc: Undo illegal license change

### PR DESCRIPTION
**Pull request by nanoscopic**
> Whether this PR is eventually merged or not, Sonic will thank you very much for your contribution. 
> 
> 无论此PR最终是否合并，Sonic组织都非常感谢您的贡献。

### Checklist

- [x] The title starts with fix, fea, or doc. | 标题为fix、feat或doc开头。
- [x] I have checked that there are no duplicate pull requests with this request. | 我已检查没有与此请求重复的拉取请求。
- [x] I have considered and confirmed that this submission is valuable to others. | 我已经考虑过，并确认这份呈件对其他人很有价值。
- [x] I accept that this submission may not be used. | 我接受此提交可能不会被使用。

### CODE REVIEW

**Comment by ZhouYixun** [comment]
Hi, @nanoscopic , nice to meet you.

This is a legal act, and the reason can be seen here -> https://opensource.org/license/mit/

> to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, **sublicense**, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

I keep the license of the original project in the `licenses` folder, and mark the original project and the original license in `README.md`

We added many functions on the basis of `gidevice`, so we sublicensed with GPLv3

**Comment by nanoscopic** [comment]
When you "sublicense" you cannot change the license terms. You can only add to them. You still remain not understanding. All the original terms must remain across the codebase. That means that you cannot add GPL restrictions to your "extensions" to an MIT project, no matter how much you might want to prevent their use under MIT terms.

Speak to a lawyer please. What you are doing is wrong.

Also, just so you are aware, gidevice illegally stole their base code from go-ios. They put it under MIT before go-ios was changed to be open under MIT as it initially was not. You are forking a project that original engaged in shady crap to begin with.

**Comment by ZhouYixun** [comment]
Hi, @nanoscopic 

https://www.tawesoft.co.uk/kb/article/mit-license-faq#:~:text=under%20another%20license%3F-,Yes.,released%20under%20your%20new%20license.

> Yes. You cannot "re-license" MIT-licensed code, and the MIT-licensed code will remain under the MIT License, but you can redistribute it as part of another project under any license you wish. You should make it clear that any changes that you make to the MIT-licensed code are released under your new license. The MIT License text & copyright notice must still be included with any unmodified MIT-licensed code.

As for what you said, gidevice is suspected to copy the go-ios code, we didn't know until you replied. But I think this is a matter between gidevice and go-ios, which should be judged by their owners.

**Comment by ZhouYixun** [comment]
We want to solve the problem in a friendly way. I don't know what the final effect you want here is

**Comment by nanoscopic** [comment]
This has been tested in courts. You cannot mix GPL and MIT code in the same compiled project.

"Project" is very vague in that it is just a collection of files. If you are compiling together GPL and MIT code, which you are, that is breaking the license.

**Comment by nanoscopic** [comment]
Stop being obtuse and read GNU's own damned FAQ: https://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense

"The GPL says that the whole combined program has to be released under the GPL."

You *cannot* include MIT code in a GPL licensed project. Stop it. You are breaking the license(s).

I don't give a crud about friendly or not. The resolution here is that you quit breaking the law and change the license on the whole project to MIT or remove all MIT content from your GPL licensed project.

**Comment by aoliaoaoaojiao** [comment]
> Stop being obtuse and read GNU's own damned FAQ: https://www.gnu.org/licenses/gpl-faq.en.html#GPLModuleLicense
> 
> "The GPL says that the whole combined program has to be released under the GPL."
> 
> You _cannot_ include MIT code in a GPL licensed project. Stop it. You are breaking the license(s).
> 
> I don't give a crud about friendly or not. The resolution here is that you quit breaking the law and change the license on the whole project to MIT or remove all MIT content from your GPL licensed project.

We will make adjustments according to the reply of fsf after consulting fsf

**Comment by nanoscopic** [comment]
The now removed cowardly comment read: "... If you are capable, please list the core codes that you think are plagiarized, and communicate with the author of go-iOS. I personally think that these iOS tools based on the dtx protocol are roughly derived from the idea of libimobiledevice. Libraries in different languages and directions refer to libimobiledevice to varying degrees, so it is normal that the core logic is similar. If you think that the similarity between the underlying dtx protocol packaging and unpacking and dtx sending and receiving logic makes you think this is plagiarism, then the ios-webkit-debug-proxy under the same language is also "plagiarizing" libimobiledevice, because its underlying dtx The logic of protocol packaging and unpacking and dtx sending and receiving is the same. I took a brief look at the code style of go-iOS, and it is not the same as gidevice. I don’t know if you want to cause a dispute between two excellent dtx tool libraries under golang, so if you think it is plagiarism, please list it Find out which places are plagiarized."

There are two people on this planet who first released open source code implementing the calls to start Xcuitests using the full DTX protocol utilizing NSKeyedArchiver. They are myself and Daniel Paulus, the author of go-ios which you speak of.

We cooperated on that work and released our separate implementations simultaneously. My implementation, iosif, is unique in that I completely reimplemented NSKeyedArchiver and NSKeyedUnarchiver from scratch based on protocol analysis. There are a few other implementations floating around, but none of them were capable of the full spec of it at the time, including those related to libimobiledevice, which I won't touch and have never referred to due to it's tainted GPL license.

I am extremely picky about my code that I have written for my own company. I own it all outright, and I have not had a need to have any of it forced into MIT or GPL because of that. I do use and compile in some MIT libraries, but I avoid GPL like the plague that it is from my point of view.

I did look at all of the existing implementing of dtx / usbmuxd protocol and all of the available public documentation when writing iosif in order to learn how it worked. I also used automatic decompilation tooling to extract the headers both from MacOS and iOS sides to learn other functionality that can be called. I implemented almost all of what you are so proud of far before anyone else on the viewable source scene did.

So trust me when I say, based on on professional opinion, as one of the very few people having implemented the entire fucking spec, that it is my strong belief that gidevice directly copy/pasted many portions of go-ios and then rewrote those bits in place to obscure that it was done. This was additionally done with libimobiledevice in the form of the rewrite of their nskeyedarechiver / nskeyedunarchiver to translate their C code to Go. That is a clear derivative and as such is an illegal change of license from GPL of libimobiledevice to MIT. electricbubble gidevice is not legal code and if you are wise you would stay away from it.

I have no issue with people learning how the protocol works looking at my code or libimobiledevice, or go-ios etc. I agree that any code done by looking, documenting the protocol sequence, and then reimplementing it, would look similar. That said, the level of similarity matters. go-ios does certain things in a very specific way that make it clear they didn't just copy the concept, they copied the exact sequence of calls ( which, by the way, don't exactly match what XCode does ) That may or may not be illegal.

Also, be aware that ALL of these implementations are breaking the Apple Developer policy. So much as publishing code doing this stuff means Apple could void your developer accounts should they choose to, not because it is generally illegal to implement their protocol, but because you agreed not to when signing up for a developer account.

I take issue with outright copying the whole damned structure of a program ( go-ios ) and then modifying it until it looks dissimilar enough to claim it wasn't initially a copy. It's total bullshit. iosif, my own implementation, I have commits from 0 showing the development process. This does not exist for gidevice, it just suddenly appeared in a much more complete form to hide its illegal origins.

After myself and Daniel Paulus released our versions ( iosif and go-ios respectively ), Alibaba released their internal implementation tidevice. pymobiledevice followed shortly after. I believe the Alibaba version is clean and they wrote from scratch themselves. pymobiledevice looks to be another copy/paste rewrite in another language, but I'm okay with that one because it was at least done very differently. It makes the same calls, as all of this stuff must, but it does not follow the same structure of any of the existing implementations.

Finally, it is really insane to think that the FSF is going to give a different response than the official GNU FAQ. Please do contact the FSF; they will just confirm what I've told you, which is that you can't implement a few extra calls and change the license of a whole project.

gidevice is bs. It is stolen code afaiac. I am hardly in a position to do anything about it because it was SO blatantly done, that the author clearly doesn't care and won't stop. I have no way to make them stop so I am limited to bitching about it. I've had extension conversation with Daniel Paulus about it; feel free to ask him yourself. I was the sole sponsor of go-ios for a while, and I essentially paid for a bunch of its implementation. I'd rather not put words in his mouth and let him speak for himself, but I will simply say that he did not disagree with me when I said it looks very clear that gidevice is outright theft.

**Comment by ZhouYixun** [comment]
We have also carried out most of the development work on the code after the fork, and we are also very concerned about the "illegal" behavior you mentioned. If fsf's answer is that we really did not re-license the license correctly, we are of course very willing to adjust to MIT.

In terms of technology, I think you are impeccable, and we respect the fruits of all labor. Comparing my heart to my heart, I will be very angry when I encounter the same situation. But the "plagiarism" you mentioned is a matter between gidevice and go-ios. I think it is up to them to decide the fate of gidevice. If Daniel points out that this is indeed a kind of plagiarism, I can stop building from gidevice. I am also communicating with Daniel today, we have always hoped to resolve the issue in an amicable and peaceful manner

**Comment by nanoscopic** [comment]
For myself, my wish is to engage in the creation of this sort of software in the most free and cooperative way that we can, while still being able to afford to live our lives and have businesses from the software we create.

I believe Daniel is in agreement with this. Neither I nor him, I think, wish to stop you from doing business.

I've mentioned this to Daniel as well, that despite the shady origin and how gidevice was built, it barely matters at this point since both go-ios and gidevice and now MIT license. That was not true in the beginning.

In some ways, GPL can be better because it forces everyone to show all modifications they make.

Others disagree and prefer MIT, because they wish to extend software internally for business purposes.

For myself, my software was released under my own custom viewable source license ( it isn't even considered "open source" by FSF ). I did so because I did not wish it to be stolen by the large megacorps.

Ultimately I wish that everyone ( myself, Daniel, your company/you, etc ) can be paid and rewarded fairly for whatever work you do to improve open source. The process of doing that is just challenging and complicated.

For myself, the peaceful solution here is just to change the license to MIT.

The remaining issue though in doing that is that gidevice is still tainted with derivative portions of libimobiledevice which is GPL. I'm not sure how that can really be resolved. You'd need to talk about that to the libimobiledevice team and ask them if they are okay with what has been done.

If libimobiledevice says that they believe parts of a derivative work, those parts would need to be replaced. Myself and/or Daniel could help you find replacement bits should that become necessary. Let's hope that is not needed, because replacing chunks of code with entirely new rewritten sections takes time and effort.

I will mention also that my main anger towards gidevice is not in any of this licensing madness... I just wish they had cooperated with me and Daniel instead of going off on their own and reimplementing the same thing. It would be a better world in my opinion where everyone cooperates on go-ios, instead of having many different implementations in Go doing the same thing. It is a waste of human effort. Where possible we should cooperate so that we don't have to spend more human labor doing something again that was done before.

I've been very open about how the software I've built works and was created, and will always continue to be this way. I don't wish to hide the techniques or knowledge. Knowledge should be freely shared for the benefit of all. I simply also would like us all to be able to get paid, and to try to follow the law / rules as best as we can.

This is why I mentioned the bit about the Apple developer agreement. At some point it is my hope that Apple will speak to all of us and agree that what we have created it acceptable. For the time being they refuse to comment. I've been trying to get them to talk to the community on this topic for years, and they just don't care and refuse every time I've asked them to talk about it.

**Comment by ZhouYixun** [comment]
Thank you for your sincere speech @nanoscopic . soniccloudorg is just an open source public welfare organization. In the past, we have only relied on donations and sponsorships and have never charged users. However, we enjoy it because we are only interested in open source and related technologies.

I am actively communicating with Daniel about the direction of cooperation. We also have different ideas for ios projection, ios touch, etc., which can be built together. I agree with you about "better world".

But in the end, I still want to wait for the reply from fsf, because most of the projects in our organization are under the GPL/AGPL agreement, the official reply will allow me to learn more about the precautions of the GPL, which may be a good practical example for comparing the provisions

**Comment by nanoscopic** [comment]
After discussion with a number of people who I consider experts on licensing issues, they have all informed me that I am badly mistaken in my understanding and that my complaining here is totally wrong.

I apologize for my lack of understanding. Despite still having a hard time believing it, multiple experts have now confirmed any MIT project can be changed to GPL at will.

As a result I apologize for complaining about this so much, as I am totally in the wrong here. Feel free to ignore me and carry on.

I do still dislike the license being changed in this way, but that is my own problem not yours. The reason I dislike it is because it prevents us from upstreaming your changes, which seems contrary to a spirit of cooperation.

Unsure what else to say here besides I'm wrong and I'm sorry.

**Comment by aoliaoaoaojiao** [comment]
> After discussion with a number of people who I consider experts on licensing issues, they have all informed me that I am badly mistaken in my understanding and that my complaining here is totally wrong.
> 
> I apologize for my lack of understanding. Despite still having a hard time believing it, multiple experts have now confirmed any MIT project can be changed to GPL at will.
> 
> As a result I apologize for complaining about this so much, as I am totally in the wrong here. Feel free to ignore me and carry on.
> 
> I do still dislike the license being changed in this way, but that is my own problem not yours. The reason I dislike it is because it prevents us from upstreaming your changes, which seems contrary to a spirit of cooperation.
> 
> Unsure what else to say here besides I'm wrong and I'm sorry.

It seems that the license issue is a misunderstanding, and we are glad that someone can come out and point out the illegal behavior of the license of the open source project.

Next we can discuss cooperation on dtx related projects. Before that, we had a brief discussion with Daniel. Of course, we are happy to cooperate here. We can also migrate some codes developed on the basis of gidevice to go-ios in our spare time, but we hope that we can discuss this matter with you and Daniel, the author of go-ios. Actively communicate and explore ways to carry out friendly cooperation. (I'm busy looking for a job and don't have a lot of free time, you guys can totally talk to my buddy @ZhouYixun who will take care of it)

**Comment by ZhouYixun** [comment]
@nanoscopic It doesn't matter who is right and who is wrong in the result. It is the knowledge we learn from the result that is the most important :)

**Pull request closed without merging**
